// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTQRksijuRH6Rtwyb3PLJt4fdck8Zqjn4',
    appId: '1:257313838147:web:d12889784744d2e021b0f6',
    messagingSenderId: '257313838147',
    projectId: 'projeto-mobile-petshop',
    authDomain: 'projeto-mobile-petshop.firebaseapp.com',
    storageBucket: 'projeto-mobile-petshop.appspot.com',
    measurementId: 'G-C5NZSWKCGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKk0wdRFtbG2Wx92quu1HcAvXn_-fWYs',
    appId: '1:257313838147:android:bcb0d58795f6b73121b0f6',
    messagingSenderId: '257313838147',
    projectId: 'projeto-mobile-petshop',
    storageBucket: 'projeto-mobile-petshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpuJNUKnLLDMITIAi5I_X-eHAirEXzRg',
    appId: '1:257313838147:ios:46bfc2ef912faa9a21b0f6',
    messagingSenderId: '257313838147',
    projectId: 'projeto-mobile-petshop',
    storageBucket: 'projeto-mobile-petshop.appspot.com',
    iosClientId: '257313838147-vmubsmp6udl57tti6n2drmephdbkb7mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXpuJNUKnLLDMITIAi5I_X-eHAirEXzRg',
    appId: '1:257313838147:ios:46bfc2ef912faa9a21b0f6',
    messagingSenderId: '257313838147',
    projectId: 'projeto-mobile-petshop',
    storageBucket: 'projeto-mobile-petshop.appspot.com',
    iosClientId: '257313838147-vmubsmp6udl57tti6n2drmephdbkb7mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
